### ISSUE TITLE
Aiming not yet included

### ISSUE THREAD

**Issue by Smooms** [SteffenKrohn/BoogeyBomber#2]
Aiming doesn't work properly yet. it's just pointing the canon at the calculated destination. But if the Enemy moves it's doing shit Nogger.

**Comment by SteffenKrohn** [comment]
Aint no thang like a prediction thang
Bud prediction depends on XML data keeping you feel me

**Comment by Smooms** [comment]
True dat!!! We jus have to keep up that nogger-shit. Younamean.

**Comment by SteffenKrohn** [comment]
Mang fo real mang
